# Configuration file for testing on travis-ci.org
language: python

python:
  #- 2.6
  - 2.7
  - 3.2
  #- 3.3

install:
  #- pip install unittest2
  - pip install novas_de405
  - python setup.py install

script:
  - python -m unittest discover novas
  #- unit2 discover novas
